name: Lint & Test
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: .node-version

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

  e2e-ios:
    needs: build
    if: contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/e2e_ios.yml

  e2e-android:
    needs: build
    if: contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/e2e_android.yml
