name: iOS Staging Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-publish:
    runs-on: macos-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: .node-version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_BASE_API_URL: ${{ vars.BASE_API_URL }}
          envkey_AUTH_STORAGE_KEY: ${{ vars.AUTH_STORAGE_KEY }}
          envkey_DEFAULT_LOCALE: ${{ vars.DEFAULT_LOCALE }}
          envkey_MOCK_API: ${{ vars.MOCK_API }}

      # Update Google Service File
      # - name: Setup Firebase File
      #   run: echo "${{ secrets.IOS_FIREBASE_FILE }}" > ./ios/GoogleService-Info.plist

      # Setup Firebase Service Account file
      #   - name: Setup Service Account Credential Files
      #     run: echo "${{secrets.FIREBASE_SERVICE_ACCOUNT_JSON}}" > "${{ github.workspace }}/firebase-service-account.json"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Cache CocoaPods
        id: cache-cocoapods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-${{ runner.arch }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-pods-

      - name: Install CocoaPods
        run: cd ios ; pod install ; cd -

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Build and Upload to Firebase
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'ios staging'
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          # FASTLANE_USER & FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD required if deploying to testflight -> lane: 'ios beta'
          # FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          # FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FIREBASE_IOS_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID }}
          #   Not required if you define service_credentials_file in the Fastfile
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
